version: 2.1
orbs:
    ruby: circleci/ruby@0.1.2
jobs:
    build:
        docker:
            - {image: 'circleci/ruby:2.7.0-node'}
            - {image: 'circleci/mysql:8.0.4', environment: {MYSQL_ROOT_PASSWORD: null, MYSQL_DATABASE: foodie_test}}
        environment:
            CC_TEST_REPORTER_ID: c729d68d1d51c3eaf08ac6e0d3ef9a4f0f27606cad91eee78a4d9d5fba52645f
        working_directory: ~/circleci-foodie-ruby-rails
        executor: ruby/default
        steps:
            - checkout
            - {run: {name: 'Install dependencies', command: "bundle -v\n- ruby/bundle-install"}}
            - {run: {name: 'Database Setup', command: "RUBYOPT='-W:no-deprecated -W:no-experimental' RAILS_ENV=test bundle exec rake db:migrate --trace\nRUBYOPT='-W:no-deprecated -W:no-experimental' bundle exec rake db:test:prepare\n"}}
            - {run: {name: 'Waiting for MySQL to be ready', command: "for i in `seq 1 10`;\ndo\n  nc -z 127.0.0.1 3306 && echo Success && exit 0\n  echo -n .\n  sleep 1\ndone\necho Failed waiting for MySQL && exit 1\n"}}
            - {run: {name: 'Setup Code Climate test-reporter', command: "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter\nchmod +x ./cc-test-reporter\n"}}
            - {run: {name: 'Run tests', command: "./cc-test-reporter before-build\nRUBYOPT='-W:no-deprecated -W:no-experimental' bundle exec rspec spec/\n./cc-test-reporter after-build --coverage-input-type clover --exit-code $?\n"}}
            - {store_test_results: {path: /tmp/test-results}}
